config/routes.rb
StoicChess::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  resources :games, only: [:create, :index, :show]
  patch 'games/:id/join', to: 'games#join', as: :join_game
  patch 'pieces/:id', to: 'pieces#move'
  get 'pieces/:id/', to: 'pieces#valid_moves'
  get 'games/:id/refresh', to: 'pieces#refresh'
  resources :users, only: [:show]

end

app/models/game.rb
# Game object that handles turn logic and board creation.
class Game < ActiveRecord::Base
  has_many :pieces, dependent: :destroy
  has_many :players, dependent: :destroy
  has_many :users, through: :players
  after_create :populate!

  def populate!
    populate_players!
    populate_pieces!
  end

  def generate_tiles
    tiles = []
    (0..7).each do |x|
      (0..7).each do |y|
        tiles << [x, y]
      end
    end
    tiles
  end

  def next_turn
    if current_player.enemy.king.in_check?
      current_player.enemy.king.in_checkmate? ? game_over! : check!
    end
    incremented_turn = turn + 1
    update(turn: incremented_turn)
  end

  def game_over!
    update(active: false)
  end

  def check!
  end

  def current_player
    turn.odd? ? white : black
  end

  def white
    players.find_by(color: 'white')
  end

  def black
    players.find_by(color: 'black')
  end

  # Returns the piece occupying the coordinates.
  def tile_occupant(x, y)
    pieces.find_by(x_position: x, y_position: y)
  end

  def tile_occupied?(x, y)
    pieces.exists?(x_position: x, y_position: y)
  end

  private

  def populate_pieces!
    populate_pawns!
    populate_knights!
    populate_bishops!
    populate_rooks!
    populate_queens!
    populate_kings!
  end

  def populate_players!
    players.create(color: 'white')
    players.create(color: 'black')
  end

  def populate_pawns!
    (0..7).each do |i|
      create_piece('Pawn', 'white', i, 6)
    end
    (0..7).each do |i|
      create_piece('Pawn', 'black', i, 1)
    end
  end

  def populate_knights!
    create_piece('Knight', 'white', 1, 7)
    create_piece('Knight', 'white', 6, 7)
    create_piece('Knight', 'black', 1, 0)
    create_piece('Knight', 'black', 6, 0)
  end

  def populate_bishops!
    create_piece('Bishop', 'white', 2, 7)
    create_piece('Bishop', 'white', 5, 7)
    create_piece('Bishop', 'black', 2, 0)
    create_piece('Bishop', 'black', 5, 0)
  end

  def populate_rooks!
    create_piece('Rook', 'white', 0, 7)
    create_piece('Rook', 'white', 7, 7)
    create_piece('Rook', 'black', 0, 0)
    create_piece('Rook', 'black', 7, 0)
  end

  def populate_queens!
    create_piece('Queen', 'white', 3, 7)
    create_piece('Queen', 'black', 3, 0)
  end

  def populate_kings!
    create_piece('King', 'white', 4, 7)
    create_piece('King', 'black', 4, 0)
  end

  def create_piece(type, color, x, y)
    if color == 'white'
      white.pieces.create(type: type, x_position: x, y_position: y,
                          color: 'white', game_id: id)
    else
      black.pieces.create(type: type, x_position: x, y_position: y,
                          color: 'black', game_id: id)
    end
  end
end

app/controllers/games_controller.rb
# Main controller for chess session for CRUD
# logic for our app
class GamesController < ApplicationController
  before_action :authenticate_user!

  def index
    @games = Game.all
  end

  def create
    @game = Game.create
    @game.white.update(user_id: current_user.id)
    redirect_to game_path(@game)
  end

  def join
    @game = Game.find(params[:id])
    @game.black.update(user_id: current_user.id)
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])
    @pieces = @game.pieces
    @player = Player.find_by(user_id: current_user.id, game_id: @game.id)
  end
end

app/helpers/games_helper.rb
# helper methods for games controller
module GamesHelper
end

app/views/games/index.html.slim
.container-fluid
  section#games-list
    | Your opponent awaits you! Join the battle!
    - @games.each do |game|
      h4 Available Game
      = button_to 'Join Game', join_game_path(game), class: 'btn btn-success pull-right'
  section#profile
    .row 
      br
      .col-sm-offset-2.col-sm-1
        |  <a class="btn btn-info dash-button" href="
        = user_path(current_user)
        | " role="button">User Dashboard
      .col-sm-offset-2.col-sm-2
        = button_to "Create Game", games_path, method: :post, class: "center-block btn btn-success btn-lg dash-button"
      .col-sm-offset-2.col-sm-1
        a.btn.btn-info[href="#" role="button"]
          | Account Settings
    br.clr
  .row
    .stats.col-sm-offset-2.col-sm-2
      h2.text-center
        = current_user.username
      = image_tag 'yoda.jpg', class: 'img-responsive'
    .stats.col-sm-offset-1.col-sm-5
      h2.text-center
        | Quick Stats
      .boxed
        h4.top
          | Games Played: 
          = current_user.games.count
        h4
          | Wins:
        h4
          | Losses:
        h4
          | Draws:

app/views/games/show.html.slim
#game
  = render 'pieces/game'