config/routes.rb
StoicChess::Application.routes.draw do
  devise_for :users
  root 'static_pages#index'

  resources :games, only: [:create, :index, :show]
  patch 'games/:id/join', to: 'games#join', as: :join_game
  patch 'pieces/:id', to: 'pieces#move'
  get 'pieces/:id/', to: 'pieces#valid_moves'
  get 'games/:id/refresh', to: 'pieces#refresh'
  resources :users, only: [:show]

end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <%= link_to 'RPGChess', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Profile', user_path(current_user) %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="form-inline">
              <div class="form-group">
                <%= f.input :email, class: 'form-control', required: false, autofocus: true %>
              </div>
              <div class="form-group">
                <%= f.input :password, class: 'form-control', required: false %>
              </div>
              <div class="form-group">
                <%= f.button :submit, "Log In", class: "btn btn-success form-control" %>
              </div>
            </div>
            <div class="form-inline">
              <div class="checkbox navbar-checkbox">
                <label>
                  <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
                </label>
              </div>
              <div class="form-group navbar-forgot-password">
                <%= render "devise/shared/forgotpassword" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RPGChess</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body class="site">
    <main class="site-content">
      <%= render "layouts/navbar" %>
      <div id='window'>
        <%= yield %>
      </div>
    </main>
      <%= render "layouts/footer" %>
  </body>
</html>